plugins {
    id 'com.android.application'
}

android {
    namespace 'com.stardevxschool.offline'
    compileSdk 34

    defaultConfig {
        applicationId "com.stardevxschool.offline"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// Tanpa dependency apa pun (tidak ada androidx / appcompat).
